name: socialcc
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.12.31=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py310h06a4308_0
  - python=3.10.16=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - ag2==0.9.10
      - annotated-types==0.7.0
      - anyio==4.11.0
      - autogen==0.9.10
      - azure-core==1.36.0
      - azure-identity==1.25.1
      - certifi==2025.10.5
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - cryptography==46.0.3
      - diskcache==5.6.3
      - distro==1.9.0
      - docker==7.1.0
      - exceptiongroup==1.3.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - jiter==0.11.1
      - msal==1.34.0
      - msal-extensions==1.3.1
      - openai==2.5.0
      - packaging==25.0
      - pycparser==2.23
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pyjwt==2.10.1
      - python-dotenv==1.1.1
      - regex==2025.9.18
      - requests==2.32.5
      - sniffio==1.3.1
      - termcolor==3.1.0
      - tiktoken==0.12.0
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
      - autogen
      - openai
prefix: /home/aiscuser/.conda/envs/socialcc
